- hosts: workstation
  gather_facts: false
  tasks:
  - name: gather openstack frontend servers
    os_server_facts:
     cloud: ospcloud
     server: 'frontend'
    register: openstack_info
    tags:
      - osp.smoke
  - name: Check haproxy is serving website
    uri:
      url: http://{{item.public_v4}}
    loop: "{{ openstack_info.ansible_facts.openstack_servers }}"
    register: webpage
    tags:
      - osp.smoke