- hosts: workstation
  gather_facts: true
  roles:
  - name: osp-facts


- name: Deploy common files to all hosts
  hosts: all:!localhost
  gather_facts: false
  roles:
   - { role: ../roles/deploy_yum_repos }

# Setup front-end load balancer tier
- name: setup load-balancer tier
  hosts: frontends
  gather_facts: true
  roles:
   - { role: ../roles/deploy_haproxy }

# Setup application servers tier

- name: setup app tier
  hosts: apps
  gather_facts: false
  roles:
   - { role: ../roles/deploy_tomcat }
   - { role: ../roles/config_tomcat }
   - { role: ../roles/deploy_apache }

# Setup database tier

- name: setup database tier
  hosts: appdbs
  gather_facts: false
  roles:
   - { role: ../roles/deploy_postgres }
