---
# vars file for osp.servers
cloud_instances:

  - webserver_name: app1
    webserver_group: apps
    deployment: QA
    flavor_name: m2.small
    security_groups: apps

  - webserver_name: app2
    webserver_group: apps
    deployment: QA
    flavor_name: m2.small
    security_groups: apps

  - webserver_name: db
    webserver_group: appdbs
    deployment: QA
    flavor_name: m2.small
    security_groups: db

  - webserver_name: frontend
    webserver_group: frontends
    deployment: QA
    flavor_name: m2.small
    security_groups: frontend